### ISSUE TITLE
The Add Profile screen should open in a dialog instead of a new browser window

### ISSUE THREAD

**Issue by svdwyer** [SolidLabResearch/solid-identity-manager#10]
Currently adding a profile will open a separate browser window.
Handling this in a standard dialog has the following benefits:
- better UX (impossible to have more than 1 popup window, no need to manage windows or having them disappear in the background)
- less complex communication
- easier state management

**Comment by pheyvaer** [comment]
So I guess we should fix this before adding new functionality, right?
