### ISSUE TITLE
Record screencast

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/solid-identity-manager#23]
- Explain what the purpose is of the extension.
- Explain how it works.
- It has to have speech.
- The speech has to be in English.

**Comment by svdwyer** [comment]
https://www.loom.com/share/9122d19ac76b4d22824df36d200c33b5
upload is taking ages, don't know why, I hope it's not stuck because it took many takes to get right.

**Comment by pheyvaer** [comment]
It doesn't play on my side. I tried different browsers. Do you by any change have the source video file? You can then send it via WeTransfer.
