### ISSUE TITLE
Querying for an IDP for a given WebID fails without proper fallback if the WebID doesn't exist or the IDP cannot be determined

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/solid-identity-manager#4]

**Comment by svdwyer** [comment]
@pheyvaer would it be sufficient to show an error message? if not, I'm not sure what the fallback should be

**Comment by pheyvaer** [comment]
Yeah, an error message is fine. We can improve later if we know of such an approach.

**Comment by svdwyer** [comment]
fixed in https://github.com/SolidLabResearch/solid-identity-manager/pull/7
