### ISSUE TITLE
Multiple buttons instead of one with popup window

### ISSUE THREAD

**Issue by pheyvaer** [SolidLabResearch/solid-identity-manager#48]
See https://github.com/SolidLabResearch/Challenges/issues/44

**Comment by pheyvaer** [comment]
@rubensworks A Chrome extension [can't have more than one icon](https://developer.chrome.com/docs/extensions/reference/api/action). It can update its icon dynamically though.

**Comment by rubensworks** [comment]
I guess you meant to ping @RubenVerborgh?

**Comment by pheyvaer** [comment]
@rubensworks Aah yes, my bad! 😅
