### ISSUE TITLE
The showcase app should display the profile display name when authenticated

### ISSUE THREAD

**Issue by svdwyer** [SolidLabResearch/solid-identity-manager#9]
Currently the app only shows a generic "you're now logged in" but doesn't show any details of the profile.
When a user has several profiles, this can be confusing

**Comment by pheyvaer** [comment]
An alternative could be that the showcase app gets the necessary information (such as name of the user) from the WebID and shows that. That way the showcase app will also show this information when the extension is not installed.

**Comment by svdwyer** [comment]
Currently the app doesn't work independent from the extension.
It shows an empty screen and throws an error.
I thought that was by design, but if it's also supposed to work without it, then your suggestion makes sense

**Comment by pheyvaer** [comment]
Yeah it should work without as well. We don't want people to impression that it's ok for Solid app to fail if the extension is not installed. At the end of the day the extension is optional, so users who don't have it should still be able to use the app.

**Comment by svdwyer** [comment]
What should the Solid app display when the extension is not installed? Currently it's a blank screen

**Comment by pheyvaer** [comment]
It should show a message saying that no extension is installed and still allow the user to login by entering their WebID/IDP manually.
